os: linux
dist: bionic
language: generic
addons:
  apt:
    packages:
      - libgmp-dev
env:
  global:
    - HACKAGE_USERNAME=fozworth
    # HACKAGE_PASSWORD
    - secure: "qRLZapirBqAfUTjcNhEYZOiC01n2NSOg15tCvKmDCimX7cv9rTSKQj+edoFfUY1FcVX7X5TQMw+bt8l0cbroOEWLZ/+J6Vsb9t45+GcNKE2T+1sC6mFNucIMfMnFEZuEgZIIxGIhsY5koWOQ0cY/FQbkpQY+hY1KlX7TjUWqaoBElnsQ6zEoMyaW/Eykkp1sOQE58OiTR9YclH9fC2vpO1lNyrIGYnCqWrgGCoUIjXyqb+qoXi3/metRPt2FfKPMZmQtPwqAwCU36uMglSZOQTMqb+6yB49STxLgwy6Xf64+9Xn5nHtBiLSfXfl35K10MgkNJ81elYCvT6DL/ZFqXAVG4bidG7sLhAqloNfIw7ZjgQZJWUs+ZKqGwL0tBtYu6h6pBIRj6aZVIilRjRH0pwzEMeoCKghgyvmQoT/zEjtTCMDxV5EHW26S5dfGvO7c0VBJviUc1teGpxg7fSouGAL2i+2oz+eueZwbFtA6BiFJC6WNK4ZsqoFukfbS1lJacwZM6uFG49hIJU/1CxlrkP5JDaF+NxNroSLby8EqJiD0jjDtE5SGlJC9BHT44tnS9s69cKbSv4dUifGCPqUnHxHtMCg/P2b1h8yEtOWs08d5RTp47KPRKh7/9VkP6djQFgtPuUlOYYcjtnu0VUIdYWQRiEKs5xVsJC5qI0IE0R8="

cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack

before_install:
  - |
    if ! test -f "$HOME/.local/bin/stack"
    then
      VERSION=2.3.0.1
      URL="https://github.com/commercialhaskell/stack/releases/download/v$VERSION/stack-$VERSION-linux-x86_64-static.tar.gz"
      curl --location --output stack.tar.gz "$URL"
      gunzip stack.tar.gz
      tar --extract --file stack.tar --strip-components 1
      mkdir --parents "$HOME/.local/bin"
      mv stack "$HOME/.local/bin"
      rm stack.tar
    fi
  - stack --version

install:
  - stack setup
  - stack build --only-dependencies --test

script:
  - stack build --no-run-tests --pedantic --test
  - stack build --test
  - stack sdist

deploy:
  provider: script
  on:
    tags: true
  skip_cleanup: true
  script: yes | stack upload .
