name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  ci:
    strategy:
      matrix:
        include:
          - { platform: ubuntu, ghc: 9.2.1 }
          - { platform: macos, ghc: 9.2.1 }
          - { platform: windows, ghc: 9.2.1, extension: .exe }
          - { platform: ubuntu, ghc: 9.0.2 }
          - { platform: ubuntu, ghc: 8.10.7 }
    runs-on: ${{ matrix.platform }}-latest
    name: GHC ${{ matrix.ghc }} on ${{ matrix.platform }}
    steps:

      - uses: actions/checkout@v2

      - id: artifact
        run: |
          mkdir artifact
          mkdir artifact/${{ matrix.platform }}
          mkdir artifact/${{ matrix.platform }}/${{ matrix.ghc }}
          echo '::set-output name=directory::artifact/${{ matrix.platform }}/${{ matrix.ghc }}'

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal configure --enable-benchmarks --flags pedantic --jobs

      - run: cabal freeze

      - run: cat cabal.project.freeze

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.platform }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.platform }}-${{ matrix.ghc }}-

      - run: cabal build

      - run: cabal bench

      - run: cabal check

      - run: cabal sdist --output-dir ${{ steps.artifact.outputs.directory }}

      - uses: actions/upload-artifact@v2
        with:
          path: artifact
          name: rampart-${{ github.sha }}

  release:
    needs: ci
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: rampart-${{ github.sha }}
          path: artifact

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/gzip
          asset_name: rampart-${{ github.event.release.tag_name }}.tar.gz
          asset_path: artifact/ubuntu/9.2.1/rampart-${{ github.event.release.tag_name }}.tar.gz
          upload_url: ${{ github.event.release.upload_url }}

      - run: cabal upload --publish --username '${{ secrets.HACKAGE_USERNAME }}' --password '${{ secrets.HACKAGE_PASSWORD }}' artifact/ubuntu/9.2.1/rampart-${{ github.event.release.tag_name }}.tar.gz
